<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Bao_duong_xe $bao_duong_xe*/ 

class c_Bao_duong_xe extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Bao_duong_xe()
    {
         parent::Controller();
         $this->load->model('bao_duong_xe');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_bao_duong_xe');        
    }  

    function readBao_duong_xe($priKey)
    {
        if(isset ($priKey))
        {
                   $this->bao_duong_xe->stt_kmbd = $priKey;
                                                                                
            $rows = $this->bao_duong_xe->read();
            foreach($rows as $row)
            {
                        echo $row->stt_kmbd."<br>";
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->khoang_muc_bao_duong."<br>";
                        echo $row->thoi_gian."<br>";
                        echo $row->speedometer."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->bao_duong_xe->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->bao_duong_xe->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_bao_duong_xe');
    }

    function read_json_format()
    {
        echo json_encode($this->bao_duong_xe->readByPagination());
    }

    function update()
    {       
        if($this->bao_duong_xe->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->bao_duong_xe->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>