<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Dm_hanhtrinh $dm_hanhtrinh*/ 

class c_Dm_hanhtrinh extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Dm_hanhtrinh()
    {
         parent::Controller();
         $this->load->model('dm_hanhtrinh');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_dm_hanhtrinh');        
    }  

    function readDm_hanhtrinh($priKey)
    {
        if(isset ($priKey))
        {
                   $this->dm_hanhtrinh->ms_hanhtrinh = $priKey;
                                                
            $rows = $this->dm_hanhtrinh->read();
            foreach($rows as $row)
            {
                        echo $row->ms_hanhtrinh."<br>";
                        echo $row->ten_hanh_trinh."<br>";
                        echo $row->so_km."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->dm_hanhtrinh->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->dm_hanhtrinh->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_dm_hanhtrinh');
    }

    function read_json_format()
    {
        echo json_encode($this->dm_hanhtrinh->readByPagination());
    }

    function update()
    {       
        if($this->dm_hanhtrinh->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->dm_hanhtrinh->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>