<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Hop_dong_thue_xe $hop_dong_thue_xe*/ 

class c_Hop_dong_thue_xe extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Hop_dong_thue_xe()
    {
         parent::Controller();
         $this->load->model('hop_dong_thue_xe');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_hop_dong_thue_xe');        
    }  

    function readHop_dong_thue_xe($priKey)
    {
        if(isset ($priKey))
        {
                   $this->hop_dong_thue_xe->so_dang_ky_xe = $priKey;
                           $this->hop_dong_thue_xe->ms_hop_dong = $priKey;
                                                                                                                                                                                                                                                
            $rows = $this->hop_dong_thue_xe->read();
            foreach($rows as $row)
            {
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->ms_hop_dong."<br>";
                        echo $row->stt_nhanvien."<br>";
                        echo $row->ms_chi_nhanh."<br>";
                        echo $row->loai_hop_dong."<br>";
                        echo $row->nguoi_tiep_nhan."<br>";
                        echo $row->km_tran."<br>";
                        echo $row->so_tien."<br>";
                        echo $row->sothuc_te."<br>";
                        echo $row->ngay_bat_dau."<br>";
                        echo $row->ngay_ket_thuc."<br>";
                        echo $row->vi_tri."<br>";
                        echo $row->dich_vu."<br>";
                        echo $row->bao_hiem."<br>";
                        echo $row->chi_phi_cho_km_them."<br>";
                        echo $row->nhuong_quyen_thuong_mai."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->hop_dong_thue_xe->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->hop_dong_thue_xe->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_hop_dong_thue_xe');
    }

    function read_json_format()
    {
        echo json_encode($this->hop_dong_thue_xe->readByPagination());
    }

    function update()
    {       
        if($this->hop_dong_thue_xe->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->hop_dong_thue_xe->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>