<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Khach_hang $khach_hang*/ 

class c_Khach_hang extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Khach_hang()
    {
        parent::Controller();
        $this->load->model('khach_hang');
        $this->load->model('VehicleDBUtils');

        $this->load->helper('form');
        $this->load->helper('object2array');
        $this->load->helper('url');
        $this->load->library('form_validation');
    }

    function index()
    {
        if(!$this->redux_auth->logged_in()){
            redirect("welcome/login");
        }
        $this->load->view('scaffolding_form/v_khach_hang');
    }

    function readKhach_hang($priKey)
    {
        if(isset ($priKey))
        {
            $this->khach_hang->stt_khachhang = $priKey;

            $rows = $this->khach_hang->read();
            foreach($rows as $row)
            {
                echo $row->stt_khachhang."<br>";
                echo $row->ten_khachhang."<br>";
                echo $row->dienthoai."<br>";
                echo $row->diachi_lienhe."<br>";
            }
        }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->khach_hang->keyAutoComplete($field_name);
        else
        echo "";
    }

    function create()
    {
        if($this->khach_hang->create())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_khach_hang');
    }

    function read_json_format()
    {
        echo json_encode($this->khach_hang->readByPagination());
    }

    function update()
    {
        if($this->khach_hang->update())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;
    }

    function delete()
    {
        if($this->khach_hang->delete())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;
    }



}
?>