<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Metadata $metadata*/ 

class c_Metadata extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Metadata()
    {
         parent::Controller();
         $this->load->model('metadata');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_metadata');        
    }  

    function readMetadata($priKey)
    {
        if(isset ($priKey))
        {
                   $this->metadata->id = $priKey;
                                                
            $rows = $this->metadata->read();
            foreach($rows as $row)
            {
                        echo $row->id."<br>";
                        echo $row->tablename."<br>";
                        echo $row->use_scaffolding."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->metadata->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->metadata->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_metadata');
    }

    function read_json_format()
    {
        echo json_encode($this->metadata->readByPagination());
    }

    function update()
    {       
        if($this->metadata->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->metadata->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>