<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Model_xe $model_xe*/ 

class c_Model_xe extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Model_xe()
    {
         parent::Controller();
         $this->load->model('model_xe');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_model_xe');        
    }  

    function readModel_xe($priKey)
    {
        if(isset ($priKey))
        {
                   $this->model_xe->ms_model_xe = $priKey;
                                                                                                                                
            $rows = $this->model_xe->read();
            foreach($rows as $row)
            {
                        echo $row->ms_model_xe."<br>";
                        echo $row->loai_model."<br>";
                        echo $row->nhan_hieu."<br>";
                        echo $row->ms_thue."<br>";
                        echo $row->nhienlieu."<br>";
                        echo $row->trongtai."<br>";
                        echo $row->dientich_san."<br>";
                        echo $row->loaixe."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->model_xe->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->model_xe->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_model_xe');
    }

    function read_json_format()
    {
        echo json_encode($this->model_xe->readByPagination());
    }

    function update()
    {       
        if($this->model_xe->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->model_xe->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>