<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Thiet_bi $thiet_bi*/ 

class c_Thiet_bi extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Thiet_bi()
    {
         parent::Controller();
         $this->load->model('thiet_bi');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_thiet_bi');        
    }  

    function readThiet_bi($priKey)
    {
        if(isset ($priKey))
        {
                   $this->thiet_bi->stt_thiet_bi = $priKey;
                                                                
            $rows = $this->thiet_bi->read();
            foreach($rows as $row)
            {
                        echo $row->stt_thiet_bi."<br>";
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->ten_thiet_bi."<br>";
                        echo $row->loai_thiet_bi."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->thiet_bi->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->thiet_bi->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_thiet_bi');
    }

    function read_json_format()
    {
        echo json_encode($this->thiet_bi->readByPagination());
    }

    function update()
    {       
        if($this->thiet_bi->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->thiet_bi->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>