<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Xe $xe*/ 

class c_Xe extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Xe()
    {
        parent::Controller();
        $this->load->model('xe');
        $this->load->model('VehicleDBUtils');

        $this->load->helper('form');
        $this->load->helper('object2array');
        $this->load->helper('url');
        $this->load->library('form_validation');
    }

    function index()
    {
        $this->load->view('scaffolding_form/v_xe');
    }

    function readXe($priKey)
    {
        if(isset ($priKey))
        {
            $this->xe->so_dang_ky_xe = $priKey;

            $rows = $this->xe->read();
            foreach($rows as $row)
            {
                echo $row->so_dang_ky_xe."<br>";
                echo $row->ms_model_xe."<br>";
                echo $row->the_tich_that."<br>";
                echo $row->url_image."<br>";
                echo $row->so_suon."<br>";
                echo $row->speedometer."<br>";
                echo $row->so_dien_thoai_tai_xe."<br>";
            }
        }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->xe->keyAutoComplete($field_name);
        else
        echo "";
    }

    function create()
    {
        if($this->xe->create())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_xe');
    }

    function read_json_format()
    {
        echo json_encode($this->xe->readByPagination());
    }

    function update()
    {
        if($this->xe->update())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;
    }

    function delete()
    {
        if($this->xe->delete())
        echo $this->messageSuccess;
        else
        echo $this->messageFail;
    }



}
?>