<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Chi_nhanh extends Model {

      //Type: String
    var $ms_chi_nhanh = '';

	  //Type: Integer
    var $stt_diem = '';

	  //Type: String
    var $ten_chi_nhanh = '';

	  //Type: String
    var $diachi = '';

	  //Type: String
    var $dienthoai = '';

	  //Type: String
    var $loai_chi_nhanh = '';

	
    function Chi_nhanh()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->chi_nhanh->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
                $this->chi_nhanh->stt_diem = $this->input->xss_clean($this->input->post('stt_diem'));
                $this->chi_nhanh->ten_chi_nhanh = $this->input->xss_clean($this->input->post('ten_chi_nhanh'));
                $this->chi_nhanh->diachi = $this->input->xss_clean($this->input->post('diachi'));
                $this->chi_nhanh->dienthoai = $this->input->xss_clean($this->input->post('dienthoai'));
                $this->chi_nhanh->loai_chi_nhanh = $this->input->xss_clean($this->input->post('loai_chi_nhanh'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Chi_nhanh->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->ms_chi_nhanh)
        {
            $this->db->where("ms_chi_nhanh", $this->ms_chi_nhanh);
        }
                if ($this->stt_diem)
        {
            $this->db->where("stt_diem", $this->stt_diem);
        }
                if ($this->ten_chi_nhanh)
        {
            $this->db->where("ten_chi_nhanh", $this->ten_chi_nhanh);
        }
                if ($this->diachi)
        {
            $this->db->where("diachi", $this->diachi);
        }
                if ($this->dienthoai)
        {
            $this->db->where("dienthoai", $this->dienthoai);
        }
                if ($this->loai_chi_nhanh)
        {
            $this->db->where("loai_chi_nhanh", $this->loai_chi_nhanh);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("chi_nhanh");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("chi_nhanh")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('chi_nhanh');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("chi_nhanh")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->ms_chi_nhanh);
                            array_push($cell, $obj->stt_diem);
                            array_push($cell, $obj->ten_chi_nhanh);
                            array_push($cell, $obj->diachi);
                            array_push($cell, $obj->dienthoai);
                            array_push($cell, $obj->loai_chi_nhanh);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                "ms_chi_nhanh" => $this->ms_chi_nhanh,
                    "stt_diem" => $this->stt_diem,
                    "ten_chi_nhanh" => $this->ten_chi_nhanh,
                    "diachi" => $this->diachi,
                    "dienthoai" => $this->dienthoai,
                    "loai_chi_nhanh" => $this->loai_chi_nhanh,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("chi_nhanh","ms_chi_nhanh", $this->ms_chi_nhanh))
        {
            $this->db->trans_start();
            $this->db->where("ms_chi_nhanh", $this->ms_chi_nhanh);
            $this->db->update("chi_nhanh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
     
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("chi_nhanh", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                 $this->chi_nhanh->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
                    $this->chi_nhanh->stt_diem = $this->input->xss_clean($this->input->post('stt_diem'));
                    $this->chi_nhanh->ten_chi_nhanh = $this->input->xss_clean($this->input->post('ten_chi_nhanh'));
                    $this->chi_nhanh->diachi = $this->input->xss_clean($this->input->post('diachi'));
                    $this->chi_nhanh->dienthoai = $this->input->xss_clean($this->input->post('dienthoai'));
                    $this->chi_nhanh->loai_chi_nhanh = $this->input->xss_clean($this->input->post('loai_chi_nhanh'));
        
        return $this->save();
    }

    function update()
    {
            $this->chi_nhanh->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
            $this->chi_nhanh->stt_diem = $this->input->xss_clean($this->input->post('stt_diem'));
            $this->chi_nhanh->ten_chi_nhanh = $this->input->xss_clean($this->input->post('ten_chi_nhanh'));
            $this->chi_nhanh->diachi = $this->input->xss_clean($this->input->post('diachi'));
            $this->chi_nhanh->dienthoai = $this->input->xss_clean($this->input->post('dienthoai'));
            $this->chi_nhanh->loai_chi_nhanh = $this->input->xss_clean($this->input->post('loai_chi_nhanh'));
    
        return $this->save();
    }

    function delete()
    {
                $this->chi_nhanh->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
                                                
        $saveSuccess = false;
         // As long as chi_nhanh->ms_chi_nhanh was set in the controller, we will delete the record.
        if ($this->ms_chi_nhanh) {
            $this->db->where("ms_chi_nhanh", $this->ms_chi_nhanh);
            $this->db->delete("chi_nhanh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
              return $saveSuccess;
    }
}

?>