<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Dm_hanhtrinh extends Model {

      //Type: Long
    var $ms_hanhtrinh = '';

	  //Type: String
    var $ten_hanh_trinh = '';

	  //Type: Double
    var $so_km = '';

	
    function Dm_hanhtrinh()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->dm_hanhtrinh->ms_hanhtrinh = $this->input->xss_clean($this->input->post('ms_hanhtrinh'));
                $this->dm_hanhtrinh->ten_hanh_trinh = $this->input->xss_clean($this->input->post('ten_hanh_trinh'));
                $this->dm_hanhtrinh->so_km = $this->input->xss_clean($this->input->post('so_km'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Dm_hanhtrinh->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->ms_hanhtrinh)
        {
            $this->db->where("ms_hanhtrinh", $this->ms_hanhtrinh);
        }
                if ($this->ten_hanh_trinh)
        {
            $this->db->where("ten_hanh_trinh", $this->ten_hanh_trinh);
        }
                if ($this->so_km)
        {
            $this->db->where("so_km", $this->so_km);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("dm_hanhtrinh");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);

        if(true  && $field_name != "ms_hanhtrinh"   )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("dm_hanhtrinh")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."$$".$obj["ten_hanh_trinh"]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('dm_hanhtrinh');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("dm_hanhtrinh")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->ms_hanhtrinh);
                            array_push($cell, $obj->ten_hanh_trinh);
                            array_push($cell, $obj->so_km);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "ten_hanh_trinh" => $this->ten_hanh_trinh,
                    "so_km" => $this->so_km,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->ms_hanhtrinh)
        {
            $this->db->trans_start();
            $this->db->where("ms_hanhtrinh", $this->ms_hanhtrinh);
            $this->db->update("dm_hanhtrinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("dm_hanhtrinh","ms_hanhtrinh", $this->ms_hanhtrinh))
        {
            $this->db->trans_start();
            $this->db->where("ms_hanhtrinh", $this->ms_hanhtrinh);
            $this->db->update("dm_hanhtrinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
  
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("dm_hanhtrinh", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                         $this->dm_hanhtrinh->ten_hanh_trinh = $this->input->xss_clean($this->input->post('ten_hanh_trinh'));
                    $this->dm_hanhtrinh->so_km = $this->input->xss_clean($this->input->post('so_km'));
        
        return $this->save();
    }

    function update()
    {
            $this->dm_hanhtrinh->ms_hanhtrinh = $this->input->xss_clean($this->input->post('ms_hanhtrinh'));
            $this->dm_hanhtrinh->ten_hanh_trinh = $this->input->xss_clean($this->input->post('ten_hanh_trinh'));
            $this->dm_hanhtrinh->so_km = $this->input->xss_clean($this->input->post('so_km'));
    
        return $this->save();
    }

    function delete()
    {
                $this->dm_hanhtrinh->ms_hanhtrinh = $this->input->xss_clean($this->input->post('ms_hanhtrinh'));
                        
        $saveSuccess = false;
         // As long as dm_hanhtrinh->ms_hanhtrinh was set in the controller, we will delete the record.
        if ($this->ms_hanhtrinh) {
            $this->db->where("ms_hanhtrinh", $this->ms_hanhtrinh);
            $this->db->delete("dm_hanhtrinh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
           return $saveSuccess;
    }
}

?>