<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Hang_hoa extends Model {

      //Type: String
    var $ms_hanghoa = '';

	  //Type: Integer
    var $stt_khachhang = '';

	  //Type: String
    var $ten_hanghoa = '';

	  //Type: Integer
    var $soluong = '';

	  //Type: String
    var $donvitinh = '';

	  //Type: String
    var $loaihang = '';

	
    function Hang_hoa()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->hang_hoa->ms_hanghoa = $this->input->xss_clean($this->input->post('ms_hanghoa'));
                $this->hang_hoa->stt_khachhang = $this->input->xss_clean($this->input->post('stt_khachhang'));
                $this->hang_hoa->ten_hanghoa = $this->input->xss_clean($this->input->post('ten_hanghoa'));
                $this->hang_hoa->soluong = $this->input->xss_clean($this->input->post('soluong'));
                $this->hang_hoa->donvitinh = $this->input->xss_clean($this->input->post('donvitinh'));
                $this->hang_hoa->loaihang = $this->input->xss_clean($this->input->post('loaihang'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Hang_hoa->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->ms_hanghoa)
        {
            $this->db->where("ms_hanghoa", $this->ms_hanghoa);
        }
                if ($this->stt_khachhang)
        {
            $this->db->where("stt_khachhang", $this->stt_khachhang);
        }
                if ($this->ten_hanghoa)
        {
            $this->db->where("ten_hanghoa", $this->ten_hanghoa);
        }
                if ($this->soluong)
        {
            $this->db->where("soluong", $this->soluong);
        }
                if ($this->donvitinh)
        {
            $this->db->where("donvitinh", $this->donvitinh);
        }
                if ($this->loaihang)
        {
            $this->db->where("loaihang", $this->loaihang);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("hang_hoa");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("hang_hoa")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('hang_hoa');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("hang_hoa")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->ms_hanghoa);
                            array_push($cell, $obj->stt_khachhang);
                            array_push($cell, $obj->ten_hanghoa);
                            array_push($cell, $obj->soluong);
                            array_push($cell, $obj->donvitinh);
                            array_push($cell, $obj->loaihang);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                "ms_hanghoa" => $this->ms_hanghoa,
                    "stt_khachhang" => $this->stt_khachhang,
                    "ten_hanghoa" => $this->ten_hanghoa,
                    "soluong" => $this->soluong,
                    "donvitinh" => $this->donvitinh,
                    "loaihang" => $this->loaihang,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("hang_hoa","ms_hanghoa", $this->ms_hanghoa))
        {
            $this->db->trans_start();
            $this->db->where("ms_hanghoa", $this->ms_hanghoa);
            $this->db->update("hang_hoa", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
     
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("hang_hoa", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                 $this->hang_hoa->ms_hanghoa = $this->input->xss_clean($this->input->post('ms_hanghoa'));
                    $this->hang_hoa->stt_khachhang = $this->input->xss_clean($this->input->post('stt_khachhang'));
                    $this->hang_hoa->ten_hanghoa = $this->input->xss_clean($this->input->post('ten_hanghoa'));
                    $this->hang_hoa->soluong = $this->input->xss_clean($this->input->post('soluong'));
                    $this->hang_hoa->donvitinh = $this->input->xss_clean($this->input->post('donvitinh'));
                    $this->hang_hoa->loaihang = $this->input->xss_clean($this->input->post('loaihang'));
        
        return $this->save();
    }

    function update()
    {
            $this->hang_hoa->ms_hanghoa = $this->input->xss_clean($this->input->post('ms_hanghoa'));
            $this->hang_hoa->stt_khachhang = $this->input->xss_clean($this->input->post('stt_khachhang'));
            $this->hang_hoa->ten_hanghoa = $this->input->xss_clean($this->input->post('ten_hanghoa'));
            $this->hang_hoa->soluong = $this->input->xss_clean($this->input->post('soluong'));
            $this->hang_hoa->donvitinh = $this->input->xss_clean($this->input->post('donvitinh'));
            $this->hang_hoa->loaihang = $this->input->xss_clean($this->input->post('loaihang'));
    
        return $this->save();
    }

    function delete()
    {
                $this->hang_hoa->ms_hanghoa = $this->input->xss_clean($this->input->post('ms_hanghoa'));
                                                
        $saveSuccess = false;
         // As long as hang_hoa->ms_hanghoa was set in the controller, we will delete the record.
        if ($this->ms_hanghoa) {
            $this->db->where("ms_hanghoa", $this->ms_hanghoa);
            $this->db->delete("hang_hoa");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
              return $saveSuccess;
    }
}

?>