<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Hop_dong_thue_xe extends Model {

    //Type: String
    var $so_dang_ky_xe = '';

    //Type: String
    var $ms_hop_dong = '';

    //Type: Long
    var $stt_nhanvien = '';

    //Type: String
    var $ms_chi_nhanh = '';

    //Type: String
    var $loai_hop_dong = '';

    //Type: String
    var $nguoi_tiep_nhan = '';

    //Type: Double
    var $km_tran = '';

    //Type: Double
    var $so_tien = '';

    //Type: Double
    var $sothuc_te = '';

    //Type:
    var $ngay_bat_dau = '';

    //Type:
    var $ngay_ket_thuc = '';

    //Type: String
    var $vi_tri = '';

    //Type: String
    var $dich_vu = '';

    //Type: String
    var $bao_hiem = '';

    //Type: Double
    var $chi_phi_cho_km_them = '';

    //Type: String
    var $nhuong_quyen_thuong_mai = '';


    function Hop_dong_thue_xe()
    {
        parent::Model();
    }

    function setFilterField()
    {
        $this->hop_dong_thue_xe->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->hop_dong_thue_xe->ms_hop_dong = $this->input->xss_clean($this->input->post('ms_hop_dong'));
        $this->hop_dong_thue_xe->stt_nhanvien = $this->input->xss_clean($this->input->post('stt_nhanvien'));
        $this->hop_dong_thue_xe->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
        $this->hop_dong_thue_xe->loai_hop_dong = $this->input->xss_clean($this->input->post('loai_hop_dong'));
        $this->hop_dong_thue_xe->nguoi_tiep_nhan = $this->input->xss_clean($this->input->post('nguoi_tiep_nhan'));
        $this->hop_dong_thue_xe->km_tran = $this->input->xss_clean($this->input->post('km_tran'));
        $this->hop_dong_thue_xe->so_tien = $this->input->xss_clean($this->input->post('so_tien'));
        $this->hop_dong_thue_xe->sothuc_te = $this->input->xss_clean($this->input->post('sothuc_te'));
        $this->hop_dong_thue_xe->ngay_bat_dau = $this->input->xss_clean($this->input->post('ngay_bat_dau'));
        $this->hop_dong_thue_xe->ngay_ket_thuc = $this->input->xss_clean($this->input->post('ngay_ket_thuc'));
        $this->hop_dong_thue_xe->vi_tri = $this->input->xss_clean($this->input->post('vi_tri'));
        $this->hop_dong_thue_xe->dich_vu = $this->input->xss_clean($this->input->post('dich_vu'));
        $this->hop_dong_thue_xe->bao_hiem = $this->input->xss_clean($this->input->post('bao_hiem'));
        $this->hop_dong_thue_xe->chi_phi_cho_km_them = $this->input->xss_clean($this->input->post('chi_phi_cho_km_them'));
        $this->hop_dong_thue_xe->nhuong_quyen_thuong_mai = $this->input->xss_clean($this->input->post('nhuong_quyen_thuong_mai'));


        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Hop_dong_thue_xe->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

        if ($this->so_dang_ky_xe)
        {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
        }
        if ($this->ms_hop_dong)
        {
            $this->db->where("ms_hop_dong", $this->ms_hop_dong);
        }
        if ($this->stt_nhanvien)
        {
            $this->db->where("stt_nhanvien", $this->stt_nhanvien);
        }
        if ($this->ms_chi_nhanh)
        {
            $this->db->where("ms_chi_nhanh", $this->ms_chi_nhanh);
        }
        if ($this->loai_hop_dong)
        {
            $this->db->where("loai_hop_dong", $this->loai_hop_dong);
        }
        if ($this->nguoi_tiep_nhan)
        {
            $this->db->where("nguoi_tiep_nhan", $this->nguoi_tiep_nhan);
        }
        if ($this->km_tran)
        {
            $this->db->where("km_tran", $this->km_tran);
        }
        if ($this->so_tien)
        {
            $this->db->where("so_tien", $this->so_tien);
        }
        if ($this->sothuc_te)
        {
            $this->db->where("sothuc_te", $this->sothuc_te);
        }
        if ($this->ngay_bat_dau)
        {
            $this->db->where("ngay_bat_dau", $this->ngay_bat_dau);
        }
        if ($this->ngay_ket_thuc)
        {
            $this->db->where("ngay_ket_thuc", $this->ngay_ket_thuc);
        }
        if ($this->vi_tri)
        {
            $this->db->where("vi_tri", $this->vi_tri);
        }
        if ($this->dich_vu)
        {
            $this->db->where("dich_vu", $this->dich_vu);
        }
        if ($this->bao_hiem)
        {
            $this->db->where("bao_hiem", $this->bao_hiem);
        }
        if ($this->chi_phi_cho_km_them)
        {
            $this->db->where("chi_phi_cho_km_them", $this->chi_phi_cho_km_them);
        }
        if ($this->nhuong_quyen_thuong_mai)
        {
            $this->db->where("nhuong_quyen_thuong_mai", $this->nhuong_quyen_thuong_mai);
        }

        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("hop_dong_thue_xe");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);

        $this->db->like($field_name, $term);

        $objects = $this->db->get("hop_dong_thue_xe")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('hop_dong_thue_xe');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
        $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("hop_dong_thue_xe")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
            array_push($cell, $obj->ms_hop_dong);
            array_push($cell, $obj->so_dang_ky_xe);            
            array_push($cell, $obj->stt_nhanvien);
            array_push($cell, $obj->ms_chi_nhanh);
            array_push($cell, $obj->loai_hop_dong);
            array_push($cell, $obj->nguoi_tiep_nhan);
            array_push($cell, $obj->km_tran);
            array_push($cell, $obj->so_tien);
            array_push($cell, $obj->sothuc_te);
            array_push($cell, $obj->ngay_bat_dau);
            array_push($cell, $obj->ngay_ket_thuc);
            array_push($cell, $obj->vi_tri);
            array_push($cell, $obj->dich_vu);
            array_push($cell, $obj->bao_hiem);
            array_push($cell, $obj->chi_phi_cho_km_them);
            array_push($cell, $obj->nhuong_quyen_thuong_mai);
            $row = new stdClass();
            $row->id = $cell[1];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey() {
        
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
            $this->db->where("ms_hop_dong", $this->ms_hop_dong);
            $rows = $this->db->get("hop_dong_thue_xe")->result();
           
            return sizeof($rows)==1;
       
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                "so_dang_ky_xe" => $this->so_dang_ky_xe,
                    "ms_hop_dong" => $this->ms_hop_dong,
                    "stt_nhanvien" => $this->stt_nhanvien,
                    "ms_chi_nhanh" => $this->ms_chi_nhanh,
                    "loai_hop_dong" => $this->loai_hop_dong,
                    "nguoi_tiep_nhan" => $this->nguoi_tiep_nhan,
                    "km_tran" => $this->km_tran,
                    "so_tien" => $this->so_tien,
                    "sothuc_te" => $this->sothuc_te,
                    "ngay_bat_dau" => $this->ngay_bat_dau,
                    "ngay_ket_thuc" => $this->ngay_ket_thuc,
                    "vi_tri" => $this->vi_tri,
                    "dich_vu" => $this->dich_vu,
                    "bao_hiem" => $this->bao_hiem,
                    "chi_phi_cho_km_them" => $this->chi_phi_cho_km_them,
                    "nhuong_quyen_thuong_mai" => $this->nhuong_quyen_thuong_mai,
        );
          $updated_db_array = array(
                    "stt_nhanvien" => $this->stt_nhanvien,
                    "ms_chi_nhanh" => $this->ms_chi_nhanh,
                    "loai_hop_dong" => $this->loai_hop_dong,
                    "nguoi_tiep_nhan" => $this->nguoi_tiep_nhan,
                    "km_tran" => $this->km_tran,
                    "so_tien" => $this->so_tien,
                    "sothuc_te" => $this->sothuc_te,
                    "ngay_bat_dau" => $this->ngay_bat_dau,
                    "ngay_ket_thuc" => $this->ngay_ket_thuc,
                    "vi_tri" => $this->vi_tri,
                    "dich_vu" => $this->dich_vu,
                    "bao_hiem" => $this->bao_hiem,
                    "chi_phi_cho_km_them" => $this->chi_phi_cho_km_them,
                    "nhuong_quyen_thuong_mai" => $this->nhuong_quyen_thuong_mai,
        );

        $saveSuccess = false;

        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey())
        {
            $this->db->trans_start();
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
            $this->db->where("ms_hop_dong", $this->ms_hop_dong);
            $this->db->update("hop_dong_thue_xe", $updated_db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }


        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("hop_dong_thue_xe", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
        $this->hop_dong_thue_xe->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->hop_dong_thue_xe->ms_hop_dong = $this->input->xss_clean($this->input->post('ms_hop_dong'));
        $this->hop_dong_thue_xe->stt_nhanvien = $this->input->xss_clean($this->input->post('stt_nhanvien'));
        $this->hop_dong_thue_xe->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
        $this->hop_dong_thue_xe->loai_hop_dong = $this->input->xss_clean($this->input->post('loai_hop_dong'));
        $this->hop_dong_thue_xe->nguoi_tiep_nhan = $this->input->xss_clean($this->input->post('nguoi_tiep_nhan'));
        $this->hop_dong_thue_xe->km_tran = $this->input->xss_clean($this->input->post('km_tran'));
        $this->hop_dong_thue_xe->so_tien = $this->input->xss_clean($this->input->post('so_tien'));
        $this->hop_dong_thue_xe->sothuc_te = $this->input->xss_clean($this->input->post('sothuc_te'));
        $this->hop_dong_thue_xe->ngay_bat_dau = $this->input->xss_clean($this->input->post('ngay_bat_dau'));
        $this->hop_dong_thue_xe->ngay_ket_thuc = $this->input->xss_clean($this->input->post('ngay_ket_thuc'));
        $this->hop_dong_thue_xe->vi_tri = $this->input->xss_clean($this->input->post('vi_tri'));
        $this->hop_dong_thue_xe->dich_vu = $this->input->xss_clean($this->input->post('dich_vu'));
        $this->hop_dong_thue_xe->bao_hiem = $this->input->xss_clean($this->input->post('bao_hiem'));
        $this->hop_dong_thue_xe->chi_phi_cho_km_them = $this->input->xss_clean($this->input->post('chi_phi_cho_km_them'));
        $this->hop_dong_thue_xe->nhuong_quyen_thuong_mai = $this->input->xss_clean($this->input->post('nhuong_quyen_thuong_mai'));

        return $this->save();
    }

    function update()
    {
        $this->hop_dong_thue_xe->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->hop_dong_thue_xe->ms_hop_dong = $this->input->xss_clean($this->input->post('ms_hop_dong'));
        $this->hop_dong_thue_xe->stt_nhanvien = $this->input->xss_clean($this->input->post('stt_nhanvien'));
        $this->hop_dong_thue_xe->ms_chi_nhanh = $this->input->xss_clean($this->input->post('ms_chi_nhanh'));
        $this->hop_dong_thue_xe->loai_hop_dong = $this->input->xss_clean($this->input->post('loai_hop_dong'));
        $this->hop_dong_thue_xe->nguoi_tiep_nhan = $this->input->xss_clean($this->input->post('nguoi_tiep_nhan'));
        $this->hop_dong_thue_xe->km_tran = $this->input->xss_clean($this->input->post('km_tran'));
        $this->hop_dong_thue_xe->so_tien = $this->input->xss_clean($this->input->post('so_tien'));
        $this->hop_dong_thue_xe->sothuc_te = $this->input->xss_clean($this->input->post('sothuc_te'));
        $this->hop_dong_thue_xe->ngay_bat_dau = $this->input->xss_clean($this->input->post('ngay_bat_dau'));
        $this->hop_dong_thue_xe->ngay_ket_thuc = $this->input->xss_clean($this->input->post('ngay_ket_thuc'));
        $this->hop_dong_thue_xe->vi_tri = $this->input->xss_clean($this->input->post('vi_tri'));
        $this->hop_dong_thue_xe->dich_vu = $this->input->xss_clean($this->input->post('dich_vu'));
        $this->hop_dong_thue_xe->bao_hiem = $this->input->xss_clean($this->input->post('bao_hiem'));
        $this->hop_dong_thue_xe->chi_phi_cho_km_them = $this->input->xss_clean($this->input->post('chi_phi_cho_km_them'));
        $this->hop_dong_thue_xe->nhuong_quyen_thuong_mai = $this->input->xss_clean($this->input->post('nhuong_quyen_thuong_mai'));

        return $this->save();
    }

    function delete()
    {
        $this->hop_dong_thue_xe->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->hop_dong_thue_xe->ms_hop_dong = $this->input->xss_clean($this->input->post('ms_hop_dong'));

        $saveSuccess = false;
        // As long as hop_dong_thue_xe->so_dang_ky_xe was set in the controller, we will delete the record.
        if ($this->so_dang_ky_xe) {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
            $this->db->delete("hop_dong_thue_xe");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
        // As long as hop_dong_thue_xe->ms_hop_dong was set in the controller, we will delete the record.
        if ($this->ms_hop_dong) {
            $this->db->where("ms_hop_dong", $this->ms_hop_dong);
            $this->db->delete("hop_dong_thue_xe");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
        return $saveSuccess;
    }
}

?>