<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Nhat_ki_hanh_trinh extends Model {

      //Type: Integer
    var $stt_nkht = '';

	  //Type: String
    var $so_dang_ky_xe = '';

	  //Type: 
    var $ngay_khoi_hanh = '';

	  //Type: String
    var $ten = '';

	  //Type: 
    var $ngay_ket_thuc_dukien = '';

	  //Type: 
    var $ngay_ket_thuc_thucte = '';

	
    function Nhat_ki_hanh_trinh()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->nhat_ki_hanh_trinh->stt_nkht = $this->input->xss_clean($this->input->post('stt_nkht'));
                $this->nhat_ki_hanh_trinh->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                $this->nhat_ki_hanh_trinh->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
                $this->nhat_ki_hanh_trinh->ten = $this->input->xss_clean($this->input->post('ten'));
                $this->nhat_ki_hanh_trinh->ngay_ket_thuc_dukien = $this->input->xss_clean($this->input->post('ngay_ket_thuc_dukien'));
                $this->nhat_ki_hanh_trinh->ngay_ket_thuc_thucte = $this->input->xss_clean($this->input->post('ngay_ket_thuc_thucte'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Nhat_ki_hanh_trinh->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->stt_nkht)
        {
            $this->db->where("stt_nkht", $this->stt_nkht);
        }
                if ($this->so_dang_ky_xe)
        {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
        }
                if ($this->ngay_khoi_hanh)
        {
            $this->db->where("ngay_khoi_hanh", $this->ngay_khoi_hanh);
        }
                if ($this->ten)
        {
            $this->db->where("ten", $this->ten);
        }
                if ($this->ngay_ket_thuc_dukien)
        {
            $this->db->where("ngay_ket_thuc_dukien", $this->ngay_ket_thuc_dukien);
        }
                if ($this->ngay_ket_thuc_thucte)
        {
            $this->db->where("ngay_ket_thuc_thucte", $this->ngay_ket_thuc_thucte);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("nhat_ki_hanh_trinh");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  && $field_name != "stt_nkht"   )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("nhat_ki_hanh_trinh")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('nhat_ki_hanh_trinh');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("nhat_ki_hanh_trinh")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->stt_nkht);
                            array_push($cell, $obj->so_dang_ky_xe);
                            array_push($cell, $obj->ngay_khoi_hanh);
                            array_push($cell, $obj->ten);
                            array_push($cell, $obj->ngay_ket_thuc_dukien);
                            array_push($cell, $obj->ngay_ket_thuc_thucte);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "so_dang_ky_xe" => $this->so_dang_ky_xe,
                    "ngay_khoi_hanh" => $this->ngay_khoi_hanh,
                    "ten" => $this->ten,
                    "ngay_ket_thuc_dukien" => $this->ngay_ket_thuc_dukien,
                    "ngay_ket_thuc_thucte" => $this->ngay_ket_thuc_thucte,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->stt_nkht)
        {
            $this->db->trans_start();
            $this->db->where("stt_nkht", $this->stt_nkht);
            $this->db->update("nhat_ki_hanh_trinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("nhat_ki_hanh_trinh","stt_nkht", $this->stt_nkht))
        {
            $this->db->trans_start();
            $this->db->where("stt_nkht", $this->stt_nkht);
            $this->db->update("nhat_ki_hanh_trinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
         // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("nhat_ki_hanh_trinh","so_dang_ky_xe", $this->so_dang_ky_xe))
        {
            $this->db->trans_start();
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
            $this->db->update("nhat_ki_hanh_trinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
         // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("nhat_ki_hanh_trinh","ngay_khoi_hanh", $this->ngay_khoi_hanh))
        {
            $this->db->trans_start();
            $this->db->where("ngay_khoi_hanh", $this->ngay_khoi_hanh);
            $this->db->update("nhat_ki_hanh_trinh", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
   
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("nhat_ki_hanh_trinh", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                         $this->nhat_ki_hanh_trinh->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                    $this->nhat_ki_hanh_trinh->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
                    $this->nhat_ki_hanh_trinh->ten = $this->input->xss_clean($this->input->post('ten'));
                    $this->nhat_ki_hanh_trinh->ngay_ket_thuc_dukien = $this->input->xss_clean($this->input->post('ngay_ket_thuc_dukien'));
                    $this->nhat_ki_hanh_trinh->ngay_ket_thuc_thucte = $this->input->xss_clean($this->input->post('ngay_ket_thuc_thucte'));
        
        return $this->save();
    }

    function update()
    {
            $this->nhat_ki_hanh_trinh->stt_nkht = $this->input->xss_clean($this->input->post('stt_nkht'));
            $this->nhat_ki_hanh_trinh->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
            $this->nhat_ki_hanh_trinh->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
            $this->nhat_ki_hanh_trinh->ten = $this->input->xss_clean($this->input->post('ten'));
            $this->nhat_ki_hanh_trinh->ngay_ket_thuc_dukien = $this->input->xss_clean($this->input->post('ngay_ket_thuc_dukien'));
            $this->nhat_ki_hanh_trinh->ngay_ket_thuc_thucte = $this->input->xss_clean($this->input->post('ngay_ket_thuc_thucte'));
    
        return $this->save();
    }

    function delete()
    {
                $this->nhat_ki_hanh_trinh->stt_nkht = $this->input->xss_clean($this->input->post('stt_nkht'));
                    $this->nhat_ki_hanh_trinh->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                    $this->nhat_ki_hanh_trinh->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
                                
        $saveSuccess = false;
         // As long as nhat_ki_hanh_trinh->stt_nkht was set in the controller, we will delete the record.
        if ($this->stt_nkht) {
            $this->db->where("stt_nkht", $this->stt_nkht);
            $this->db->delete("nhat_ki_hanh_trinh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
          // As long as nhat_ki_hanh_trinh->so_dang_ky_xe was set in the controller, we will delete the record.
        if ($this->so_dang_ky_xe) {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
            $this->db->delete("nhat_ki_hanh_trinh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
          // As long as nhat_ki_hanh_trinh->ngay_khoi_hanh was set in the controller, we will delete the record.
        if ($this->ngay_khoi_hanh) {
            $this->db->where("ngay_khoi_hanh", $this->ngay_khoi_hanh);
            $this->db->delete("nhat_ki_hanh_trinh");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
            return $saveSuccess;
    }
}

?>