<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Van_chuyen extends Model {

    //Type: String
    var $ma_chuyen = '';

    //Type: String
    var $so_dang_ky_xe = '';

    //Type: Long
    var $ms_hanhtrinh = '';

    //Type:
    var $ngay_khoi_hanh = '';

    //Type:
    var $ngay_ket_thuc_dukien = '';

    //Type:
    var $ngay_ket_thuc_thucte = '';


    function Van_chuyen()
    {
        parent::Model();
    }

    function setFilterField()
    {
        $this->van_chuyen->ma_chuyen = $this->input->xss_clean($this->input->post('ma_chuyen'));
        $this->van_chuyen->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->van_chuyen->ms_hanhtrinh = $this->input->xss_clean($this->input->post('ms_hanhtrinh'));
        $this->van_chuyen->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
        $this->van_chuyen->ngay_ket_thuc_dukien = $this->input->xss_clean($this->input->post('ngay_ket_thuc_dukien'));
        $this->van_chuyen->ngay_ket_thuc_thucte = $this->input->xss_clean($this->input->post('ngay_ket_thuc_thucte'));

        if ($this->ma_chuyen)
        {
            $this->db->where("ma_chuyen", $this->ma_chuyen);
        }
        if ($this->so_dang_ky_xe)
        {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
        }
        if ($this->ms_hanhtrinh)
        {
            $this->db->where("ms_hanhtrinh", $this->ms_hanhtrinh);
        }
        if ($this->ngay_khoi_hanh)
        {
            $this->db->where("ngay_khoi_hanh", $this->ngay_khoi_hanh);
        }
        if ($this->ngay_ket_thuc_dukien)
        {
            $this->db->where("ngay_ket_thuc_dukien", $this->ngay_ket_thuc_dukien);
        }
        if ($this->ngay_ket_thuc_thucte)
        {
            $this->db->where("ngay_ket_thuc_thucte", $this->ngay_ket_thuc_thucte);
        }

        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("van_chuyen");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);

        if(true  )
        $this->db->like($field_name, $term);

        $objects = $this->db->get("van_chuyen")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');
        $mode = $this->input->post('mode');

        if(!$sidx) {$sidx =1;}
        $count = $this->db->count_all('van_chuyen');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
        $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");

        if($mode == "short"){
            $so_van_don =  $this->input->post('so_van_don',TRUE);
            $sql = "";
            if($so_van_don != null){
                $sql = "SELECT * FROM van_chuyen WHERE ma_chuyen IN (SELECT ma_chuyen FROM chi_tiet_van_don WHERE so_van_don = ";
                $sql = $sql . "'" . $so_van_don . "')";
            }
            $objects = $this->db->query($sql)->result();
        }
        else {
            $this->setFilterField();
            $objects = $this->db->get("van_chuyen")->result();
        }

        $rows =  array();
        foreach($objects as $obj)
        {
            $cell = array();
            if($mode == "short"){
                array_push($cell, $obj->ma_chuyen);
                array_push($cell, $obj->ngay_khoi_hanh);
                array_push($cell, $obj->ngay_ket_thuc_dukien);
            }
            else {
                array_push($cell, $obj->ma_chuyen);
                array_push($cell, $obj->so_dang_ky_xe);
                array_push($cell, $obj->ms_hanhtrinh);
                array_push($cell, $obj->ngay_khoi_hanh);
                array_push($cell, $obj->ngay_ket_thuc_dukien);
                array_push($cell, $obj->ngay_ket_thuc_thucte);
            }

            $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                "ma_chuyen" => $this->ma_chuyen,
                    "so_dang_ky_xe" => $this->so_dang_ky_xe,
                    "ms_hanhtrinh" => $this->ms_hanhtrinh,
                    "ngay_khoi_hanh" => $this->ngay_khoi_hanh,
                    "ngay_ket_thuc_dukien" => $this->ngay_ket_thuc_dukien,
                    "ngay_ket_thuc_thucte" => $this->ngay_ket_thuc_thucte,
        );

        $saveSuccess = false;

        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("van_chuyen","ma_chuyen", $this->ma_chuyen))
        {
            $this->db->trans_start();
            $this->db->where("ma_chuyen", $this->ma_chuyen);
            $this->db->update("van_chuyen", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }

        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("van_chuyen", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
        $this->van_chuyen->ma_chuyen = $this->input->xss_clean($this->input->post('ma_chuyen'));
        $this->van_chuyen->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->van_chuyen->ms_hanhtrinh = $this->input->xss_clean($this->input->post('ms_hanhtrinh'));
        $this->van_chuyen->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
        $this->van_chuyen->ngay_ket_thuc_dukien = $this->input->xss_clean($this->input->post('ngay_ket_thuc_dukien'));
        $this->van_chuyen->ngay_ket_thuc_thucte = $this->input->xss_clean($this->input->post('ngay_ket_thuc_thucte'));

        return $this->save();
    }

    function update()
    {
        $this->van_chuyen->ma_chuyen = $this->input->xss_clean($this->input->post('ma_chuyen'));
        $this->van_chuyen->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
        $this->van_chuyen->ms_hanhtrinh = $this->input->xss_clean($this->input->post('ms_hanhtrinh'));
        $this->van_chuyen->ngay_khoi_hanh = $this->input->xss_clean($this->input->post('ngay_khoi_hanh'));
        $this->van_chuyen->ngay_ket_thuc_dukien = $this->input->xss_clean($this->input->post('ngay_ket_thuc_dukien'));
        $this->van_chuyen->ngay_ket_thuc_thucte = $this->input->xss_clean($this->input->post('ngay_ket_thuc_thucte'));

        return $this->save();
    }

    function delete()
    {
        $this->van_chuyen->ma_chuyen = $this->input->xss_clean($this->input->post('ma_chuyen'));

        $saveSuccess = false;
        // As long as van_chuyen->ma_chuyen was set in the controller, we will delete the record.
        if ($this->ma_chuyen) {
            $this->db->where("ma_chuyen", $this->ma_chuyen);
            $this->db->delete("van_chuyen");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
        return $saveSuccess;
    }
}

?>