<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Bat_thuong extends Model {

      //Type: Integer
    var $stt_bt = '';

	  //Type: String
    var $so_dang_ky_xe = '';

	  //Type: String
    var $loai_bat_thuong = '';

	  //Type: String
    var $mo_ta_bat_thuong = '';

	  //Type: Double
    var $speedometer = '';

	
    function Bat_thuong()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->bat_thuong->stt_bt = $this->input->xss_clean($this->input->post('stt_bt'));
                $this->bat_thuong->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                $this->bat_thuong->loai_bat_thuong = $this->input->xss_clean($this->input->post('loai_bat_thuong'));
                $this->bat_thuong->mo_ta_bat_thuong = $this->input->xss_clean($this->input->post('mo_ta_bat_thuong'));
                $this->bat_thuong->speedometer = $this->input->xss_clean($this->input->post('speedometer'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Bat_thuong->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->stt_bt)
        {
            $this->db->where("stt_bt", $this->stt_bt);
        }
                if ($this->so_dang_ky_xe)
        {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
        }
                if ($this->loai_bat_thuong)
        {
            $this->db->where("loai_bat_thuong", $this->loai_bat_thuong);
        }
                if ($this->mo_ta_bat_thuong)
        {
            $this->db->where("mo_ta_bat_thuong", $this->mo_ta_bat_thuong);
        }
                if ($this->speedometer)
        {
            $this->db->where("speedometer", $this->speedometer);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("bat_thuong");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  && $field_name != "stt_bt"   )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("bat_thuong")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('bat_thuong');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("bat_thuong")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->stt_bt);
                            array_push($cell, $obj->so_dang_ky_xe);
                            array_push($cell, $obj->loai_bat_thuong);
                            array_push($cell, $obj->mo_ta_bat_thuong);
                            array_push($cell, $obj->speedometer);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "so_dang_ky_xe" => $this->so_dang_ky_xe,
                    "loai_bat_thuong" => $this->loai_bat_thuong,
                    "mo_ta_bat_thuong" => $this->mo_ta_bat_thuong,
                    "speedometer" => $this->speedometer,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->stt_bt)
        {
            $this->db->trans_start();
            $this->db->where("stt_bt", $this->stt_bt);
            $this->db->update("bat_thuong", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("bat_thuong","stt_bt", $this->stt_bt))
        {
            $this->db->trans_start();
            $this->db->where("stt_bt", $this->stt_bt);
            $this->db->update("bat_thuong", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
    
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("bat_thuong", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                         $this->bat_thuong->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                    $this->bat_thuong->loai_bat_thuong = $this->input->xss_clean($this->input->post('loai_bat_thuong'));
                    $this->bat_thuong->mo_ta_bat_thuong = $this->input->xss_clean($this->input->post('mo_ta_bat_thuong'));
                    $this->bat_thuong->speedometer = $this->input->xss_clean($this->input->post('speedometer'));
        
        return $this->save();
    }

    function update()
    {
            $this->bat_thuong->stt_bt = $this->input->xss_clean($this->input->post('stt_bt'));
            $this->bat_thuong->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
            $this->bat_thuong->loai_bat_thuong = $this->input->xss_clean($this->input->post('loai_bat_thuong'));
            $this->bat_thuong->mo_ta_bat_thuong = $this->input->xss_clean($this->input->post('mo_ta_bat_thuong'));
            $this->bat_thuong->speedometer = $this->input->xss_clean($this->input->post('speedometer'));
    
        return $this->save();
    }

    function delete()
    {
                $this->bat_thuong->stt_bt = $this->input->xss_clean($this->input->post('stt_bt'));
                                        
        $saveSuccess = false;
         // As long as bat_thuong->stt_bt was set in the controller, we will delete the record.
        if ($this->stt_bt) {
            $this->db->where("stt_bt", $this->stt_bt);
            $this->db->delete("bat_thuong");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
             return $saveSuccess;
    }
}

?>