<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Khach_hang extends Model {

      //Type: Integer
    var $stt_khachhang = '';

	  //Type: String
    var $ten_khachhang = '';

	  //Type: String
    var $dienthoai = '';

	  //Type: String
    var $diachi_lienhe = '';

	
    function Khach_hang()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->khach_hang->stt_khachhang = $this->input->xss_clean($this->input->post('stt_khachhang'));
                $this->khach_hang->ten_khachhang = $this->input->xss_clean($this->input->post('ten_khachhang'));
                $this->khach_hang->dienthoai = $this->input->xss_clean($this->input->post('dienthoai'));
                $this->khach_hang->diachi_lienhe = $this->input->xss_clean($this->input->post('diachi_lienhe'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Khach_hang->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->stt_khachhang)
        {
            $this->db->where("stt_khachhang", $this->stt_khachhang);
        }
                if ($this->ten_khachhang)
        {
            $this->db->where("ten_khachhang", $this->ten_khachhang);
        }
                if ($this->dienthoai)
        {
            $this->db->where("dienthoai", $this->dienthoai);
        }
                if ($this->diachi_lienhe)
        {
            $this->db->where("diachi_lienhe", $this->diachi_lienhe);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("khach_hang");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  && $field_name != "stt_khachhang"   )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("khach_hang")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('khach_hang');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("khach_hang")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->stt_khachhang);
                            array_push($cell, $obj->ten_khachhang);
                            array_push($cell, $obj->dienthoai);
                            array_push($cell, $obj->diachi_lienhe);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "ten_khachhang" => $this->ten_khachhang,
                    "dienthoai" => $this->dienthoai,
                    "diachi_lienhe" => $this->diachi_lienhe,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->stt_khachhang)
        {
            $this->db->trans_start();
            $this->db->where("stt_khachhang", $this->stt_khachhang);
            $this->db->update("khach_hang", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("khach_hang","stt_khachhang", $this->stt_khachhang))
        {
            $this->db->trans_start();
            $this->db->where("stt_khachhang", $this->stt_khachhang);
            $this->db->update("khach_hang", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
   
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("khach_hang", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                         $this->khach_hang->ten_khachhang = $this->input->xss_clean($this->input->post('ten_khachhang'));
                    $this->khach_hang->dienthoai = $this->input->xss_clean($this->input->post('dienthoai'));
                    $this->khach_hang->diachi_lienhe = $this->input->xss_clean($this->input->post('diachi_lienhe'));
        
        return $this->save();
    }

    function update()
    {
            $this->khach_hang->stt_khachhang = $this->input->xss_clean($this->input->post('stt_khachhang'));
            $this->khach_hang->ten_khachhang = $this->input->xss_clean($this->input->post('ten_khachhang'));
            $this->khach_hang->dienthoai = $this->input->xss_clean($this->input->post('dienthoai'));
            $this->khach_hang->diachi_lienhe = $this->input->xss_clean($this->input->post('diachi_lienhe'));
    
        return $this->save();
    }

    function delete()
    {
                $this->khach_hang->stt_khachhang = $this->input->xss_clean($this->input->post('stt_khachhang'));
                                
        $saveSuccess = false;
         // As long as khach_hang->stt_khachhang was set in the controller, we will delete the record.
        if ($this->stt_khachhang) {
            $this->db->where("stt_khachhang", $this->stt_khachhang);
            $this->db->delete("khach_hang");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
            return $saveSuccess;
    }
}

?>