<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Loaihang extends Model {

    //Type: Long
    var $ms_loaihang = '';

    //Type: String
    var $ten_loaihang = '';

    //Type: String
    var $dac_tinh = '';


    function Loaihang()
    {
        parent::Model();
    }

    function setFilterField()
    {
        $this->loaihang->ms_loaihang = $this->input->xss_clean($this->input->post('ms_loaihang'));
        $this->loaihang->ten_loaihang = $this->input->xss_clean($this->input->post('ten_loaihang'));
        $this->loaihang->dac_tinh = $this->input->xss_clean($this->input->post('dac_tinh'));


        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Loaihang->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

        if ($this->ms_loaihang)
        {
            $this->db->where("ms_loaihang", $this->ms_loaihang);
        }
        if ($this->ten_loaihang)
        {
            $this->db->where("ten_loaihang", $this->ten_loaihang);
        }
        if ($this->dac_tinh)
        {
            $this->db->where("dac_tinh", $this->dac_tinh);
        }

        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("loaihang");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  )
        $this->db->like($field_name, $term);

        $objects = $this->db->get("loaihang")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('loaihang');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
        $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("loaihang")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
            array_push($cell, $obj->ms_loaihang);
            array_push($cell, $obj->ten_loaihang);
            array_push($cell, $obj->dac_tinh);
            $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                "ms_loaihang" => $this->ms_loaihang,
                    "ten_loaihang" => $this->ten_loaihang,
                    "dac_tinh" => $this->dac_tinh,
        );

        $saveSuccess = false;

        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("loaihang","ms_loaihang", $this->ms_loaihang))
        {
            $this->db->trans_start();
            $this->db->where("ms_loaihang", $this->ms_loaihang);
            $this->db->update("loaihang", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }

        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("loaihang", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
        $this->loaihang->ms_loaihang = $this->input->xss_clean($this->input->post('ms_loaihang'));
        $this->loaihang->ten_loaihang = $this->input->xss_clean($this->input->post('ten_loaihang'));
        $this->loaihang->dac_tinh = $this->input->xss_clean($this->input->post('dac_tinh'));

        return $this->save();
    }

    function update()
    {
        $this->loaihang->ms_loaihang = $this->input->xss_clean($this->input->post('ms_loaihang'));
        $this->loaihang->ten_loaihang = $this->input->xss_clean($this->input->post('ten_loaihang'));
        $this->loaihang->dac_tinh = $this->input->xss_clean($this->input->post('dac_tinh'));

        return $this->save();
    }

    function delete()
    {
        $this->loaihang->ms_loaihang = $this->input->xss_clean($this->input->post('ms_loaihang'));

        $saveSuccess = false;
        // As long as loaihang->ms_loaihang was set in the controller, we will delete the record.
        if ($this->ms_loaihang) {
            $this->db->where("ms_loaihang", $this->ms_loaihang);
            $this->db->delete("loaihang");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
        return $saveSuccess;
    }
}

?>