<?php
//Model is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Input $input
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
*/ 

class Thiet_bi extends Model {

      //Type: Long
    var $stt_thiet_bi = '';

	  //Type: String
    var $so_dang_ky_xe = '';

	  //Type: String
    var $ten_thiet_bi = '';

	  //Type: String
    var $loai_thiet_bi = '';

	
    function Thiet_bi()
    {
        parent::Model();
    }

    function setFilterField()
    {
                $this->thiet_bi->stt_thiet_bi = $this->input->xss_clean($this->input->post('stt_thiet_bi'));
                $this->thiet_bi->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                $this->thiet_bi->ten_thiet_bi = $this->input->xss_clean($this->input->post('ten_thiet_bi'));
                $this->thiet_bi->loai_thiet_bi = $this->input->xss_clean($this->input->post('loai_thiet_bi'));
        

        // BEGIN FILTER CRITERIA CHECK
        // If any of the following properties are set before Thiet_bi->get() is called from the controller then we will include
        // a where statement for each of the properties that have been set.

                if ($this->stt_thiet_bi)
        {
            $this->db->where("stt_thiet_bi", $this->stt_thiet_bi);
        }
                if ($this->so_dang_ky_xe)
        {
            $this->db->where("so_dang_ky_xe", $this->so_dang_ky_xe);
        }
                if ($this->ten_thiet_bi)
        {
            $this->db->where("ten_thiet_bi", $this->ten_thiet_bi);
        }
                if ($this->loai_thiet_bi)
        {
            $this->db->where("loai_thiet_bi", $this->loai_thiet_bi);
        }
        
        // END FILTER CRITERIA CHECK
    }

    function read()
    {
        $this->setFilterField();

        // This will execute the query and collect the results and other properties of the query into an object.
        $query = $this->db->get("thiet_bi");

        return $query->result();
    }

    //please remove this if you need more security
    function keyAutoComplete($field_name) {
        $term = $this->input->post("q");
        $limit = $this->input->post("limit");

        $this->db->limit($limit);



        if(true  && $field_name != "stt_thiet_bi"   )
          $this->db->like($field_name, $term);     

        $objects = $this->db->get("thiet_bi")->result_array();

        foreach($objects as $obj)
        {
            echo $obj[$field_name]."\n";
        }
    }


    //TODO: check XSS and SQL injection here
    function readByPagination()
    {
        $limit = $this->input->post('rows');
        $page = $this->input->post('page');
        $sidx = $this->input->post('sidx');
        $sord = $this->input->post('sord');

        if(!$sidx) $sidx =1;
        $count = $this->db->count_all('thiet_bi');

        if( $count >0 ) {
            $total_pages = ceil($count/$limit);
        } else {
            $total_pages = 0;
        }
        if ($page > $total_pages)
            $page=$total_pages;
        $start = $limit * $page - $limit;

        $this->db->limit($limit, $start);
        $this->db->order_by("$sidx", "$sord");
        $this->setFilterField();

        $objects = $this->db->get("thiet_bi")->result();
        $rows =  array();

        foreach($objects as $obj)
        {
            $cell = array();
                            array_push($cell, $obj->stt_thiet_bi);
                            array_push($cell, $obj->so_dang_ky_xe);
                            array_push($cell, $obj->ten_thiet_bi);
                            array_push($cell, $obj->loai_thiet_bi);
                        $row = new stdClass();
            $row->id = $cell[0];
            $row->cell = $cell;
            array_push($rows, $row);
        }

        $jsonObject = new stdClass();
        $jsonObject->page =  $page;
        $jsonObject->total = $total_pages;
        $jsonObject->records = $count;
        $jsonObject->rows = $rows;

        return $jsonObject;
    }

    private function isUsedKey($table,$keyName, $keyValue) {
        if($keyValue)  {
            $this->db->where($keyName, $keyValue);
            $rows = $this->db->get($table)->result();
            return sizeof($rows)==1;
        }
        return false;
    }

    private function save()
    {
        // When we insert or update a record in CodeIgniter, we pass the results as an array:
        $db_array = array(
                    "so_dang_ky_xe" => $this->so_dang_ky_xe,
                    "ten_thiet_bi" => $this->ten_thiet_bi,
                    "loai_thiet_bi" => $this->loai_thiet_bi,
          );

      $saveSuccess = false;

         // If key was set in the controller, then we will update an existing record.
        if ($this->stt_thiet_bi)
        {
            $this->db->trans_start();
            $this->db->where("stt_thiet_bi", $this->stt_thiet_bi);
            $this->db->update("thiet_bi", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
        // If key was set in the controller, then we will update an existing record.
        if ($this->isUsedKey("thiet_bi","stt_thiet_bi", $this->stt_thiet_bi))
        {
            $this->db->trans_start();
            $this->db->where("stt_thiet_bi", $this->stt_thiet_bi);
            $this->db->update("thiet_bi", $db_array);
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
            $this->db->trans_complete();
            return $saveSuccess;
        }
   
        // If key was not set in the controller, then we will insert a new record.
        $this->db->trans_start();
        $this->db->insert("thiet_bi", $db_array);
        if($this->db->affected_rows() > 0) {
            $saveSuccess = true;
        }
        else {
            $saveSuccess = false;
        }
        $this->db->trans_complete();
        return $saveSuccess;
    }

    function create()
    {
                         $this->thiet_bi->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
                    $this->thiet_bi->ten_thiet_bi = $this->input->xss_clean($this->input->post('ten_thiet_bi'));
                    $this->thiet_bi->loai_thiet_bi = $this->input->xss_clean($this->input->post('loai_thiet_bi'));
        
        return $this->save();
    }

    function update()
    {
            $this->thiet_bi->stt_thiet_bi = $this->input->xss_clean($this->input->post('stt_thiet_bi'));
            $this->thiet_bi->so_dang_ky_xe = $this->input->xss_clean($this->input->post('so_dang_ky_xe'));
            $this->thiet_bi->ten_thiet_bi = $this->input->xss_clean($this->input->post('ten_thiet_bi'));
            $this->thiet_bi->loai_thiet_bi = $this->input->xss_clean($this->input->post('loai_thiet_bi'));
    
        return $this->save();
    }

    function delete()
    {
                $this->thiet_bi->stt_thiet_bi = $this->input->xss_clean($this->input->post('stt_thiet_bi'));
                                
        $saveSuccess = false;
         // As long as thiet_bi->stt_thiet_bi was set in the controller, we will delete the record.
        if ($this->stt_thiet_bi) {
            $this->db->where("stt_thiet_bi", $this->stt_thiet_bi);
            $this->db->delete("thiet_bi");
            if($this->db->affected_rows() > 0) {
                $saveSuccess = true;
            }
            else {
                $saveSuccess = false;
            }
        }
            return $saveSuccess;
    }
}

?>