<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Bat_thuong $bat_thuong*/ 

class c_Bat_thuong extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Bat_thuong()
    {
         parent::Controller();
         $this->load->model('bat_thuong');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_bat_thuong');        
    }  

    function readBat_thuong($priKey)
    {
        if(isset ($priKey))
        {
                   $this->bat_thuong->stt_bt = $priKey;
                                                                                
            $rows = $this->bat_thuong->read();
            foreach($rows as $row)
            {
                        echo $row->stt_bt."<br>";
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->loai_bat_thuong."<br>";
                        echo $row->mo_ta_bat_thuong."<br>";
                        echo $row->speedometer."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->bat_thuong->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->bat_thuong->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_bat_thuong');
    }

    function read_json_format()
    {
        echo json_encode($this->bat_thuong->readByPagination());
    }

    function update()
    {       
        if($this->bat_thuong->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->bat_thuong->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>