<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Chi_nhanh $chi_nhanh*/ 

class c_Chi_nhanh extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Chi_nhanh()
    {
         parent::Controller();
         $this->load->model('chi_nhanh');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_chi_nhanh');        
    }  

    function readChi_nhanh($priKey)
    {
        if(isset ($priKey))
        {
                   $this->chi_nhanh->ms_chi_nhanh = $priKey;
                                                                                                
            $rows = $this->chi_nhanh->read();
            foreach($rows as $row)
            {
                        echo $row->ms_chi_nhanh."<br>";
                        echo $row->stt_diem."<br>";
                        echo $row->ten_chi_nhanh."<br>";
                        echo $row->diachi."<br>";
                        echo $row->dienthoai."<br>";
                        echo $row->loai_chi_nhanh."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->chi_nhanh->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->chi_nhanh->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_chi_nhanh');
    }

    function read_json_format()
    {
        echo json_encode($this->chi_nhanh->readByPagination());
    }

    function update()
    {       
        if($this->chi_nhanh->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->chi_nhanh->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>