<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Chi_tiet_van_don $chi_tiet_van_don*/ 

class c_Chi_tiet_van_don extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Chi_tiet_van_don()
    {
         parent::Controller();
         $this->load->model('chi_tiet_van_don');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_chi_tiet_van_don');        
    }  

    function readChi_tiet_van_don($priKey)
    {
        if(isset ($priKey))
        {
                   $this->chi_tiet_van_don->so_van_don = $priKey;
                           $this->chi_tiet_van_don->ms_hanghoa = $priKey;
                                                                                                                                                                                
            $rows = $this->chi_tiet_van_don->read();
            foreach($rows as $row)
            {
                        echo $row->so_van_don."<br>";
                        echo $row->ms_hanghoa."<br>";
                        echo $row->ma_chuyen."<br>";
                        echo $row->ms_loaihang."<br>";
                        echo $row->ten_hang."<br>";
                        echo $row->so_luong."<br>";
                        echo $row->khoi_luong."<br>";
                        echo $row->quy_cach_dong_goi."<br>";
                        echo $row->trangthai_hanghoa."<br>";
                        echo $row->nguoinhan."<br>";
                        echo $row->diachi_nhan."<br>";
                        echo $row->cuoc."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->chi_tiet_van_don->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->chi_tiet_van_don->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_chi_tiet_van_don');
    }

    function read_json_format()
    {
        echo json_encode($this->chi_tiet_van_don->readByPagination());
    }

    function update()
    {       
        if($this->chi_tiet_van_don->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->chi_tiet_van_don->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>