<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Loaihang $loaihang*/ 

class c_Loaihang extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Loaihang()
    {
         parent::Controller();
         $this->load->model('loaihang');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_loaihang');        
    }  

    function readLoaihang($priKey)
    {
        if(isset ($priKey))
        {
                   $this->loaihang->ms_loaihang = $priKey;
                                                
            $rows = $this->loaihang->read();
            foreach($rows as $row)
            {
                        echo $row->ms_loaihang."<br>";
                        echo $row->ten_loaihang."<br>";
                        echo $row->dac_tinh."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->loaihang->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->loaihang->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_loaihang');
    }

    function read_json_format()
    {
        echo json_encode($this->loaihang->readByPagination());
    }

    function update()
    {       
        if($this->loaihang->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->loaihang->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>