<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Nhat_ki_hanh_trinh $nhat_ki_hanh_trinh*/ 

class c_Nhat_ki_hanh_trinh extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Nhat_ki_hanh_trinh()
    {
         parent::Controller();
         $this->load->model('nhat_ki_hanh_trinh');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_nhat_ki_hanh_trinh');        
    }  

    function readNhat_ki_hanh_trinh($priKey)
    {
        if(isset ($priKey))
        {
                   $this->nhat_ki_hanh_trinh->stt_nkht = $priKey;
                           $this->nhat_ki_hanh_trinh->so_dang_ky_xe = $priKey;
                           $this->nhat_ki_hanh_trinh->ngay_khoi_hanh = $priKey;
                                                                
            $rows = $this->nhat_ki_hanh_trinh->read();
            foreach($rows as $row)
            {
                        echo $row->stt_nkht."<br>";
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->ngay_khoi_hanh."<br>";
                        echo $row->ten."<br>";
                        echo $row->ngay_ket_thuc_dukien."<br>";
                        echo $row->ngay_ket_thuc_thucte."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->nhat_ki_hanh_trinh->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->nhat_ki_hanh_trinh->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_nhat_ki_hanh_trinh');
    }

    function read_json_format()
    {
        echo json_encode($this->nhat_ki_hanh_trinh->readByPagination());
    }

    function update()
    {       
        if($this->nhat_ki_hanh_trinh->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->nhat_ki_hanh_trinh->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>