<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Thuoc_tinh_mo_rong_cua_xe $thuoc_tinh_mo_rong_cua_xe*/ 

class c_Thuoc_tinh_mo_rong_cua_xe extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Thuoc_tinh_mo_rong_cua_xe()
    {
         parent::Controller();
         $this->load->model('thuoc_tinh_mo_rong_cua_xe');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_thuoc_tinh_mo_rong_cua_xe');        
    }  

    function readThuoc_tinh_mo_rong_cua_xe($priKey)
    {
        if(isset ($priKey))
        {
                   $this->thuoc_tinh_mo_rong_cua_xe->so_dang_ky_xe = $priKey;
                           $this->thuoc_tinh_mo_rong_cua_xe->ten = $priKey;
                                
            $rows = $this->thuoc_tinh_mo_rong_cua_xe->read();
            foreach($rows as $row)
            {
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->ten."<br>";
                        echo $row->gia_tri."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->thuoc_tinh_mo_rong_cua_xe->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->thuoc_tinh_mo_rong_cua_xe->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_thuoc_tinh_mo_rong_cua_xe');
    }

    function read_json_format()
    {
        echo json_encode($this->thuoc_tinh_mo_rong_cua_xe->readByPagination());
    }

    function update()
    {       
        if($this->thuoc_tinh_mo_rong_cua_xe->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->thuoc_tinh_mo_rong_cua_xe->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>