<?php
//Controller is generated by MVC Schema Engine

/**
* @property CI_Loader $load
* @property CI_Form_validation $form_validation
* @property CI_Input $input
* @property CI_Email $email
* @property CI_DB_active_record $db
* @property CI_DB_forge $dbforge
* @property VehicleDBUtils $VehicleDBUtils
* @property Van_chuyen $van_chuyen*/ 

class c_Van_chuyen extends Controller
{
    //message in vietnamese, TODO: add I18N later
    var $messageSuccess = "Thành công";
    var $messageFail    = "Thất bại";

    function c_Van_chuyen()
    {
         parent::Controller();
         $this->load->model('van_chuyen');
         $this->load->model('VehicleDBUtils');

         $this->load->helper('form');
         $this->load->helper('object2array');
         $this->load->helper('url');
         $this->load->library('form_validation');
    }

    function index()
    {       
        $this->load->view('scaffolding_form/v_van_chuyen');        
    }  

    function readVan_chuyen($priKey)
    {
        if(isset ($priKey))
        {
                   $this->van_chuyen->ma_chuyen = $priKey;
                                                                                                
            $rows = $this->van_chuyen->read();
            foreach($rows as $row)
            {
                        echo $row->ma_chuyen."<br>";
                        echo $row->so_dang_ky_xe."<br>";
                        echo $row->ms_hanhtrinh."<br>";
                        echo $row->ngay_khoi_hanh."<br>";
                        echo $row->ngay_ket_thuc_dukien."<br>";
                        echo $row->ngay_ket_thuc_thucte."<br>";
                        }
         }
    }

    function keyAutoComplete($field_name = "")
    {
        if($field_name != "")
        $this->van_chuyen->keyAutoComplete($field_name);
        else
         echo "";
    }

    function create()
    {
        if($this->van_chuyen->create())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }

    function read()
    {
        $this->load->view('v_van_chuyen');
    }

    function read_json_format()
    {
        echo json_encode($this->van_chuyen->readByPagination());
    }

    function update()
    {       
        if($this->van_chuyen->update())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;        
    }

    function delete()
    {
        if($this->van_chuyen->delete())
            echo $this->messageSuccess;
        else
            echo $this->messageFail;
    }


    
}
?>